defaultBaseImage: registry.access.redhat.com/ubi9/ubi-minimal

baseImageOverrides:
  github.com/shipwright-io/build/cmd/git: ghcr.io/shipwright-io/base-git:latest
  github.com/shipwright-io/build/cmd/waiter: ghcr.io/shipwright-io/base-waiter:latest
  github.com/shipwright-io/build/cmd/image-processing: boatyard/image-processing:dev
